# Google Cloud Build configuration for Cloud Run deployment
# Uses Artifact Registry (GCR deprecated) + gen2 runtime + europe-west1

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/indian-address-parser:${_TAG}',
           '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/indian-address-parser:latest',
           '--build-arg', 'HF_MODEL_REPO=${_HF_MODEL_REPO}',
           '-f', 'api/Dockerfile', '.']

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/indian-address-parser']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'indian-address-parser',
           '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/indian-address-parser:${_TAG}',
           '--region', '${_REGION}',
           '--platform', 'managed',
           '--execution-environment', 'gen2',
           '--memory', '4Gi',
           '--cpu', '2',
           '--min-instances', '1',
           '--max-instances', '10',
           '--cpu-boost',
           '--no-cpu-throttling',
           '--timeout', '300',
           '--concurrency', '10',
           '--allow-unauthenticated',
           '--set-env-vars', 'MODEL_PATH=/app/models/address_ner_v4,DEVICE=cpu,TORCHDYNAMO_DISABLE=1']

substitutions:
  _REGION: europe-west1
  _REPO: indian-address-parser
  _HF_MODEL_REPO: x2aqq/indian-address-parser-model
  _TAG: v1

options:
  logging: CLOUD_LOGGING_ONLY
