# Google Cloud Build configuration for Cloud Run deployment

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/indian-address-parser:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/indian-address-parser:latest'
      - '-f'
      - 'api/Dockerfile'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/indian-address-parser:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/indian-address-parser:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'indian-address-parser'
      - '--image'
      - 'gcr.io/$PROJECT_ID/indian-address-parser:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'  # Zero cold start
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MODEL_PATH=/app/models/address_ner,DEVICE=cpu'

images:
  - 'gcr.io/$PROJECT_ID/indian-address-parser:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/indian-address-parser:latest'

options:
  logging: CLOUD_LOGGING_ONLY
